#!/bin/bash
# 检查几何求解器是否真正被使用

echo "=========================================="
echo "几何求解器使用情况诊断"
echo "=========================================="
echo ""

echo "1. 配置文件检查"
echo "----------------------------------------"
echo "geometric_solver.enabled:"
grep "enabled:" /home/ilex/Dev/VIST/config/system_config.yaml | grep -A 1 "geometric_solver:" | tail -1

echo ""
echo "disable_differential_ik:"
grep "disable_differential_ik:" /home/ilex/Dev/VIST/config/system_config.yaml | grep -v "#"

echo ""
echo "2. 代码检查"
echo "----------------------------------------"
echo ""
echo "vist_kalman_filter.py 中 geometric_solver 的使用:"
grep -n "self.geometric_solver" /home/ilex/Dev/VIST/ros2_ws/src/core/vist_kalman_filter.py

echo ""
echo "3. 结论"
echo "----------------------------------------"
echo ""
echo "❌ 问题发现："
echo ""
echo "1. 配置文件显示:"
echo "   - geometric_solver.enabled: true"
echo "   - disable_differential_ik: true"
echo ""
echo "2. 但是代码中:"
echo "   - geometric_solver 只在 __init__ 中被赋值"
echo "   - 从未在 update() 或其他方法中被调用"
echo "   - disable_differential_ik 参数根本没有被读取"
echo ""
echo "3. 实际情况:"
echo "   - 几何求解器被初始化了（日志显示 GeometricSolver 初始化完成）"
echo "   - 但是 VIST 从未使用它！"
echo "   - 虚拟引导仍然使用微分IK计算（filters.py 第217-299行）"
echo ""
echo "4. 这意味着:"
echo "   - 你的配置 disable_differential_ik: true 没有生效"
echo "   - 几何求解器只是被创建了，但从未被调用"
echo "   - 系统仍在使用微分IK（较慢，可能不稳定）"
echo ""
echo "=========================================="
echo "影响分析"
echo "=========================================="
echo ""
echo "这可能是导致抖动的一个原因："
echo ""
echo "1. 微分IK的问题:"
echo "   - 使用雅可比伪逆，在奇异点附近不稳定"
echo "   - 需要迭代求解，计算量大"
echo "   - 可能产生不自然的关节配置"
echo ""
echo "2. 几何求解器的优势（但未被使用）:"
echo "   - 解析解，速度快10-100倍"
echo "   - 配置唯一且自然"
echo "   - 符合人体运动学"
echo "   - 避免奇异点问题"
echo ""
echo "3. 建议:"
echo "   - 需要修改代码，让VIST真正使用几何求解器"
echo "   - 或者暂时禁用几何求解器（避免浪费资源）"
echo ""