#!/usr/bin/env python3
"""
VIST频率波动诊断报告
分析 /filtered_left_joint_control 话题频率不稳定的原因
"""

print("=" * 70)
print("VIST 频率波动诊断报告")
print("=" * 70)
print()

print("问题现象:")
print("  /filtered_left_joint_control 话题频率不定时从80Hz突变到40-60Hz")
print()

print("=" * 70)
print("发现的问题")
print("=" * 70)
print()

print("1. 【严重】频繁的print()调用阻塞主循环")
print("   位置: ros2_ws/src/core/vist_kalman_filter.py")
print("   问题代码:")
print("     - 第848-880行: 每0.5秒打印一次调试信息")
print("     - 第851行: print(f'[VIST] α=...')")
print("     - 第855行: print(f'[VIST] 输入输出差异...')")
print("     - 第862行: print(f'[VIST] 观测噪声...')")
print("     - 第868行: print(f'[VIST] 过程噪声...')")
print("     - 第873行: print(f'[VIST] 卡尔曼增益范数...')")
print("     - 第878行: print(f'[VIST] 创新向量范数...')")
print("     - 第880行: print('')  # 空行")
print()
print("   影响:")
print("     - print()是同步I/O操作，会阻塞线程")
print("     - 每次打印约耗时1-5ms")
print("     - 80Hz = 12.5ms周期，打印占用40%时间")
print("     - 导致定时器回调延迟，频率下降")
print()

print("2. 【中等】频繁的time.time()调用")
print("   位置: ros2_ws/src/core/vist_kalman_filter.py")
print("   问题代码:")
print("     - 第589行: current_time = time.time()  # 动态dt计算")
print("     - 第848行: current_time = time.time()  # 打印时间检查")
print()
print("   影响:")
print("     - 每次update()调用2次time.time()")
print("     - 虽然开销小，但累积影响性能")
print()

print("3. 【轻微】复杂的矩阵运算")
print("   位置: ros2_ws/src/core/vist_kalman_filter.py")
print("   问题代码:")
print("     - 第860-868行: 计算矩阵对角线平均值用于打印")
print("     - 第872行: np.linalg.norm(K)  # 计算增益范数")
print("     - 第877行: np.linalg.norm(innovation)  # 计算创新范数")
print()
print("   影响:")
print("     - 这些计算仅用于调试输出")
print("     - 在80Hz循环中不应该执行")
print()

print("=" * 70)
print("根本原因分析")
print("=" * 70)
print()

print("定时器设计:")
print("  - 期望频率: 80Hz")
print("  - 定时器周期: 12.5ms")
print("  - 实际执行时间: 应该 < 12.5ms")
print()

print("实际执行时间分解:")
print("  1. 滤波计算: ~5-8ms (卡尔曼滤波、FK、雅可比)")
print("  2. print()输出: ~1-5ms (每0.5秒触发一次)")
print("  3. 其他开销: ~1-2ms")
print("  总计: ~7-15ms")
print()

print("当print()触发时:")
print("  - 执行时间: 13-15ms > 12.5ms")
print("  - 定时器延迟触发")
print("  - 频率下降到 1/0.015 ≈ 67Hz")
print("  - 或者跳过一个周期，频率降到40Hz")
print()

print("=" * 70)
print("解决方案")
print("=" * 70)
print()

print("方案1: 【推荐】禁用调试打印")
print("  修改: ros2_ws/src/core/vist_kalman_filter.py")
print("  操作: 注释掉第848-880行的打印代码")
print("  或者: 将 alpha_print_interval 设置为更大的值（如5秒）")
print()

print("方案2: 使用ROS2日志系统")
print("  替换: print() → self.get_logger().debug()")
print("  优点: 可以通过日志级别控制，不影响性能")
print("  缺点: 需要传递logger对象到滤波器")
print()

print("方案3: 异步日志")
print("  使用: 单独的日志线程")
print("  优点: 完全不阻塞主循环")
print("  缺点: 实现复杂")
print()

print("方案4: 减少打印频率")
print("  修改: alpha_print_interval = 0.5 → 5.0")
print("  效果: 每5秒打印一次，影响降低10倍")
print()

print("=" * 70)
print("快速修复")
print("=" * 70)
print()

print("立即生效的修复:")
print()
print("1. 编辑文件:")
print("   vim ros2_ws/src/core/vist_kalman_filter.py")
print()
print("2. 找到第163行:")
print("   self.alpha_print_interval = 0.5")
print()
print("3. 修改为:")
print("   self.alpha_print_interval = 5.0  # 或者更大")
print()
print("4. 或者完全禁用打印:")
print("   注释掉第848-880行")
print()
print("5. 重启VIST节点")
print()

print("=" * 70)
print("验证修复")
print("=" * 70)
print()

print("1. 检查话题频率:")
print("   ros2 topic hz /filtered_left_joint_control")
print()
print("   预期输出: 稳定在 80Hz ± 1Hz")
print()

print("2. 运行频率监控:")
print("   python3 diagnose_angle_units.py")
print()

print("3. 查看可视化:")
print("   python3 visualize_robot_realtime.py")
print()
print("   终端应显示: 更新频率: 80 Hz (稳定)")
print()

print("=" * 70)
print("性能优化建议")
print("=" * 70)
print()

print("长期优化:")
print("  1. 移除所有print()，使用ROS2日志")
print("  2. 减少不必要的time.time()调用")
print("  3. 避免在主循环中计算调试信息")
print("  4. 使用性能分析工具找出瓶颈")
print()

print("监控指标:")
print("  - 定时器回调频率: 应该稳定在80Hz")
print("  - 滤波输出频率: 应该稳定在80Hz")
print("  - 回调执行时间: 应该 < 12ms")
print()

print("=" * 70)
