#!/bin/bash
# VIST 机械臂抖动问题诊断和修复

echo "=========================================="
echo "VIST 机械臂抖动问题诊断"
echo "=========================================="
echo ""

# Source 工作空间
source /home/ilex/Dev/VIST/ros2_ws/install/setup.bash

echo "1. 当前意图因子状态"
echo "----------------------------------------"
timeout 2 ros2 topic echo /vist_intent_factors --once 2>&1 | grep -A 5 "data:"
echo ""

echo "2. 当前性能数据"
echo "----------------------------------------"
timeout 2 ros2 topic echo /vist_performance --once 2>&1 | grep -A 7 "data:"
echo ""

echo "3. 问题分析"
echo "----------------------------------------"
echo ""
echo "根据日志分析，发现以下问题："
echo ""
echo "❌ 问题1: 意图因子α过高 (0.81-0.88)"
echo "   - α接近1表示系统处于\"约束模式\""
echo "   - 此时XY约束方差仅为0.01 (约1.8°)"
echo "   - 系统会强烈抵抗操作者的输入"
echo ""
echo "❌ 问题2: 几何因子为0 (geo=0.000)"
echo "   - 距离感知失效"
echo "   - 系统无法根据距离调整意图"
echo "   - 导致α值异常偏高"
echo ""
echo "❌ 问题3: 速度和方向因子饱和 (vel=1.0, dir=1.0)"
echo "   - 系统认为操作者\"完全对准目标\""
echo "   - 触发最强约束"
echo ""
echo "❌ 问题4: 频率不匹配"
echo "   - 配置dt=0.0125s (80Hz)"
echo "   - 但VIST内部可能使用dt=0.02s (50Hz)"
echo "   - 导致速度计算错误"
echo ""
echo "❌ 问题5: 约束方差过紧"
echo "   - cons_variance_xyz=[0.01, 0.01, 1.0]"
echo "   - 0.01 rad² ≈ 0.03 rad ≈ 1.8°"
echo "   - 太紧会导致\"卡死\"感"
echo ""

echo "4. 根本原因"
echo "----------------------------------------"
echo ""
echo "机械臂抖动的根本原因："
echo ""
echo "1. 【参数过紧】约束方差0.01太小，系统过度约束"
echo "2. 【意图检测失效】几何因子为0，距离感知不工作"
echo "3. 【高α锁定】系统长期处于高约束状态(α≈0.88)"
echo "4. 【频率失配】控制频率与滤波器dt不匹配"
echo ""
echo "当α=0.88时，实际方差为："
echo "  Σ = (1-α)·Σ_free + α·Σ_cons"
echo "  Σ = 0.12×1.0 + 0.88×0.01 = 0.129 rad²"
echo ""
echo "这个方差仍然很小，导致系统对操作者输入响应迟钝，"
echo "操作者需要用更大的力才能移动，产生\"打架\"和抖动。"
echo ""

echo "5. 推荐修复方案"
echo "----------------------------------------"
echo ""
echo "方案A: 放宽约束方差（推荐）"
echo "  cons_variance_xyz: [0.05, 0.05, 1.0]  # 从0.01增加到0.05"
echo "  - 增加5倍，给操作者更多控制权"
echo "  - 仍保持一定约束感"
echo ""
echo "方案B: 降低意图权重"
echo "  w_geo: 0.3  # 从0.5降低到0.3"
echo "  w_vel: 0.7  # 从0.5增加到0.7"
echo "  - 减少几何因子影响"
echo "  - 增加速度因子影响，更跟随操作者"
echo ""
echo "方案C: 增加意图平滑"
echo "  intent_smoothing: 0.9  # 从0.7增加到0.9"
echo "  - 让α变化更平滑"
echo "  - 减少突变导致的抖动"
echo ""
echo "方案D: 修复频率不匹配"
echo "  确保 filter_system.dt = 0.0125 (80Hz)"
echo "  - 与控制频率一致"
echo ""
echo "方案E: 临时禁用VIST（测试用）"
echo "  filter_type: 'gello'  # 切换到直通模式"
echo "  - 验证是否是VIST参数问题"
echo ""

echo "6. 快速测试建议"
echo "----------------------------------------"
echo ""
echo "步骤1: 先测试直通模式"
echo "  修改 baseline_filters_config.yaml:"
echo "  filter_type: 'gello'"
echo "  重启节点，观察是否还抖动"
echo ""
echo "步骤2: 如果直通模式正常，说明是VIST参数问题"
echo "  恢复 filter_type: 'vist'"
echo "  修改 system_config.yaml:"
echo "  cons_variance_xyz: [0.1, 0.1, 1.0]  # 大幅放宽"
echo ""
echo "步骤3: 逐步调优"
echo "  从0.1开始，逐步减小到找到合适值"
echo "  目标: 既有约束感，又不会\"打架\""
echo ""

echo "=========================================="
echo "诊断完成"
echo "=========================================="