#!/bin/bash
# VIST 角度单位诊断和修复指南

echo "=========================================="
echo "VIST 角度单位诊断和修复指南"
echo "=========================================="
echo ""

echo "问题症状:"
echo "  - Meshcat中机械臂四处乱甩"
echo "  - 关节角度异常大或异常小"
echo "  - 运动不符合预期"
echo ""

echo "可能原因:"
echo "  ⚠️  角度单位不一致（弧度 vs 角度）"
echo ""

echo "数据流检查点:"
echo "  1. 外骨骼输入: /robot1/left_arm/exo_hand_joint_control"
echo "  2. 视觉输入: /robot1/left_arm/vision_joint_control"
echo "  3. 机械臂反馈: /robot1/left_arm/joint_states"
echo "  4. 滤波输出: /filtered_left_joint_control"
echo "  5. Pinocchio可视化: 必须使用弧度"
echo ""

echo "=========================================="
echo "诊断步骤"
echo "=========================================="
echo ""

echo "步骤1: 运行角度单位诊断工具"
echo "  python3 diagnose_angle_units.py"
echo ""
echo "  该工具会:"
echo "  - 监听所有相关话题"
echo "  - 自动检测角度单位"
echo "  - 报告不一致问题"
echo ""

echo "步骤2: 手动检查话题数据"
echo "  # 查看滤波输出"
echo "  ros2 topic echo /filtered_left_joint_control --once"
echo ""
echo "  # 查看机械臂反馈"
echo "  ros2 topic echo /robot1/left_arm/joint_states --once"
echo ""
echo "  判断标准:"
echo "  - 弧度: 通常在 -π 到 π 之间 (-3.14 到 3.14)"
echo "  - 角度: 通常在 -180° 到 180° 之间"
echo ""

echo "=========================================="
echo "已实施的修复"
echo "=========================================="
echo ""

echo "1. vist_filter_node.py (第547-553行)"
echo "   ✓ 自动检测机械臂反馈是否为角度"
echo "   ✓ 如果 max(|q|) > 10，自动转换为弧度"
echo ""

echo "2. visualize_robot_realtime.py (第116-134行)"
echo "   ✓ 接收数据时检测单位"
echo "   ✓ 如果检测到角度，自动转换为弧度"
echo "   ✓ 输出警告信息"
echo ""

echo "=========================================="
echo "验证修复"
echo "=========================================="
echo ""

echo "1. 启动VIST系统"
echo "   # 启动机械臂和VIST节点"
echo ""

echo "2. 运行诊断工具"
echo "   python3 diagnose_angle_units.py"
echo ""
echo "   预期输出:"
echo "   - 所有数据源应显示相同单位"
echo "   - 滤波输出应为弧度"
echo "   - 无警告信息"
echo ""

echo "3. 运行可视化"
echo "   python3 visualize_robot_realtime.py"
echo ""
echo "   预期行为:"
echo "   - 机械臂运动平滑"
echo "   - 无异常甩动"
echo "   - 如果有单位转换，会显示警告"
echo ""

echo "=========================================="
echo "常见问题"
echo "=========================================="
echo ""

echo "Q: 为什么会出现角度/弧度混用？"
echo "A: 不同设备可能使用不同单位:"
echo "   - 外骨骼: 可能输出角度"
echo "   - 视觉系统: 可能输出角度"
echo "   - 机械臂驱动: 可能使用角度"
echo "   - Pinocchio: 必须使用弧度"
echo ""

echo "Q: 如何确认数据单位？"
echo "A: 查看数值范围:"
echo "   - 弧度: -3.14 ~ 3.14 (±π)"
echo "   - 角度: -180 ~ 180"
echo "   - 如果看到 >10 的值，很可能是角度"
echo ""

echo "Q: 修复后还是乱甩怎么办？"
echo "A: 检查其他可能原因:"
echo "   - 关节顺序是否正确"
echo "   - 关节限位是否合理"
echo "   - 滤波器参数是否合适"
echo "   - 运行: python3 diagnose_angle_units.py"
echo ""

echo "=========================================="
echo "技术细节"
echo "=========================================="
echo ""

echo "单位转换公式:"
echo "  弧度 = 角度 × π / 180"
echo "  角度 = 弧度 × 180 / π"
echo ""

echo "NumPy函数:"
echo "  np.deg2rad(degrees)  # 角度转弧度"
echo "  np.rad2deg(radians)  # 弧度转角度"
echo ""

echo "检测阈值:"
echo "  if max(|q|) > 10:"
echo "    # 很可能是角度（因为 10 rad ≈ 573°）"
echo "    # 正常关节角度不会超过 ±π (±3.14)"
echo ""

echo "=========================================="