#!/bin/bash
# 机械臂Meshcat实时可视化使用指南

echo "=========================================="
echo "机械臂Meshcat实时可视化"
echo "=========================================="
echo ""
echo "脚本: visualize_robot_realtime.py"
echo "订阅话题: /filtered_left_joint_control"
echo ""

echo "功能:"
echo "  ✓ 订阅ROS2关节控制话题"
echo "  ✓ 实时显示机械臂运动状态"
echo "  ✓ 完整3D模型可视化"
echo "  ✓ 显示更新频率统计"
echo ""

echo "使用方法:"
echo "  1. 确保ROS2系统正在运行"
echo "  2. 确保 /filtered_left_joint_control 话题正在发布"
echo "  3. 运行可视化脚本:"
echo "     python3 visualize_robot_realtime.py"
echo ""

echo "检查话题:"
echo "  # 查看话题列表"
echo "  ros2 topic list | grep filtered"
echo ""
echo "  # 查看话题频率"
echo "  ros2 topic hz /filtered_left_joint_control"
echo ""
echo "  # 查看话题内容"
echo "  ros2 topic echo /filtered_left_joint_control --once"
echo ""

echo "操作提示:"
echo "  - 脚本启动后会自动打开浏览器"
echo "  - 在浏览器中可以看到机械臂实时运动"
echo "  - 终端会显示更新频率和关节角度"
echo "  - 鼠标左键: 旋转视图"
echo "  - 鼠标右键: 平移视图"
echo "  - 滚轮: 缩放视图"
echo "  - 按 Ctrl+C 停止"
echo ""

echo "预期输出:"
echo "  更新频率: 80 Hz | 关节角度: [0.00, -0.50, 0.00, -1.50, 0.00, 1.00, 0.00]"
echo ""

echo "故障排除:"
echo "  1. 如果没有数据更新:"
echo "     - 检查话题是否存在: ros2 topic list"
echo "     - 检查话题是否发布: ros2 topic hz /filtered_left_joint_control"
echo ""
echo "  2. 如果模型不显示:"
echo "     - 检查mesh文件是否存在"
echo "     - 查看终端错误信息"
echo ""

echo "=========================================="
